### ISSUE TITLE
Add as npm package, to be used as dependency

### ISSUE THREAD

**Issue by rollecode** [lendk/Lint-HTML-with-SCSS-CSS#2]
It would be great to have this in npm, so you could just add it to your project as dependency and get updates directly from the repo. What do you think? I'd find use for it, that's for sure.

**Comment by lendk** [comment]
Will do later today :)

**Comment by rollecode** [comment]
Amazing! 🐱  no rush.

**Comment by lendk** [comment]
The deed has been done hahahahaha, `npm install lint-html-with-scss-css`, or see the [npm page](https://www.npmjs.com/package/lint-html-with-scss-css)

**Comment by rollecode** [comment]
Thank you for the great deed, sir. Appreciate it. 👌
